#!/bin/bash

cd "${0%/*}"

if [ -z $PYTHON ]; then
  if command -v python3 &> /dev/null; then
    PYTHON=python3
  elif command -v python &> /dev/null; then
    PYTHON=python
  else
    echo "Python not found"
    exit 1
  fi
fi

$PYTHON -m dotfileslib.main $*
