add_newline = false

format = """
[\ue70f](bright-cyan) \
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
\
$line_break\
\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

[line_break]
disabled = false

[character]
success_symbol = "[\ufb26](bold green)"
error_symbol = "[\ufb26](bold red)"
