[settings]
disable_backends = ["asdf"]
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = false

[settings.python]
compile = false

[tools]
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:ClementTsang/bottom" = "0.12.3"
"aqua:ajeetdsouza/zoxide" = "0.9.9"
"aqua:astral-sh/uv" = "0.11.7"
"aqua:cli/cli" = "2.91.0"
"aqua:go-task/task" = "3.50.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.71.0"
"aqua:lsd-rs/lsd" = "1.2.0"
"aqua:orhun/git-cliff" = "2.12.0"
"aqua:pnpm/pnpm" = "10.33.0"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.4.2"
"aqua:sharkdp/hyperfine" = "1.20.0"
"aqua:topgrade-rs/topgrade" = "17.3.0"
"aqua:x-motemen/ghq" = "1.10.1"
"aqua:lima-vm/lima" = { version = "2.1.1", os = ["macos"] }
"cargo:cargo-audit" = "0.22.1"
"cargo:cargo-bloat" = "0.12.1"
"cargo:cargo-cache" = "0.8.3"
"cargo:cargo-edit" = "0.13.8"
"cargo:cargo-update" = "20.0.0"
"cargo:gitlogue" = "0.9.0"
"cargo:random-output" = "0.3.1"
"cargo:tealdeer" = "1.8.1"
"cargo:tokei" = "14.0.0"
"npm:@google/gemini-cli" = "0.38.2"
"npm:tiged" = "2.12.7"
"npm:trash-cli" = "7.2.0"
node = "25.9.0"
python = "3.14.4"
rust = { version = "1.95.0", components = "rust-src,rust-analyzer" }
