[settings]
disable_backends = ["asdf"]
idiomatic_version_file_enable_tools = []
minimum_release_age = "7d"

[settings.cargo]
binstall = false

[settings.python]
compile = false

[tools]
"aqua:BurntSushi/ripgrep" = "15.2.0"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:ajeetdsouza/zoxide" = "0.10.0"
"aqua:astral-sh/uv" = "0.12.6"
"aqua:aws/aws-cli" = { version = "2.36.34", os = ["linux"] }
"aqua:chmln/sd" = "1.1.0"
"aqua:cli/cli" = "2.98.0"
"aqua:cloudflare/cloudflared" = "2026.8.2"
"aqua:fastfetch-cli/fastfetch" = "2.67.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.74.3"
"aqua:k1LoW/git-wt" = "0.29.1"
"aqua:lima-vm/lima" = { version = "2.2.0", os = ["macos"] }
"aqua:lsd-rs/lsd" = "1.2.0"
"aqua:ogulcancelik/herdr" = { version = "0.8.2", os = ["linux", "macos"] }
"aqua:openai/codex" = { version = "0.144.1", os = ["linux", "macos"] }
"aqua:pnpm/pnpm" = "11.24.0"
"aqua:qpdf/qpdf" = "12.4.0"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.4.2"
"aqua:topgrade-rs/topgrade" = "17.9.0"
"aqua:tree-sitter/tree-sitter" = "0.26.13"
"aqua:x-motemen/ghq" = "1.10.1"
"cargo:cargo-audit" = "0.22.2"
"cargo:https://github.com/yuma140902/grid-images" = { version = "tag:v0.1.0", os = ["windows"] }
"cargo:random-output" = "0.3.6"
"cargo:tealdeer" = "1.9.0"
"cargo:tokei" = "14.0.0"
"github:psmux/psmux" = { version = "3.3.8", os = ["windows"] }
"npm:tiged" = "2.12.8"
"npm:trash-cli" = { version = "7.2.0", os = ["windows"] }
"pipx:marimo" = "0.24.0"
"pipx:trash-cli" = { version = "0.24.5.26", os = ["linux", "macos"] }
"vfox:mise-plugins/vfox-neovim" = "0.12.2"
node = "25.9.0"
python = "3.14.7"
rust = { version = "1.98.0", components = "rust-src,rust-analyzer" }

[bootstrap.packages]
# brew backend ではバージョン指定がまだサポートされていないので仕方なく latest を指定する
"brew:gcc" = "latest"
"brew:git" = "latest"
"brew:git-lfs" = "latest"
"brew:htop" = "latest"
"brew:mise" = "latest"
"brew:tig" = "latest"
"brew:tmux" = "latest"
"brew:wget" = "latest"
"brew:zstd" = "latest"
