FROM ubuntu:resolute-20260627@sha256:b7f48194d4d8b763a478a621cdc81c27be222ba2206ca3ca6bc42b49685f3d9e
RUN apt update && apt install -y git curl build-essential libssl-dev pkg-config zsh python3
COPY .. /root/repos/dotfiles-public
