FROM nixos/nix:2.34.7@sha256:bf1d938835ab96312f098fa6c2e9cab367728e0aad0646ee3e02a787c80d8fb8
RUN echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf

# remove pre-installed conflicting packages
RUN nix-env -e less man-db git-minimal wget curl

COPY .. /root/repos/dotfiles-public
