FROM ubuntu:resolute-20260610@sha256:53958ec7b67c2c9355df922dd08dbf0360611f8c3cdb656875e81873db9ffdba
RUN apt update && apt install -y git curl build-essential libssl-dev pkg-config zsh python3
COPY .. /root/repos/dotfiles-public
