FROM ubuntu:resolute-20260724.1@sha256:678c6550cc43645e08669028bc177f50be4e7c5b8cca677067b1914d4afc7a03
RUN apt update && apt install -y git curl build-essential libssl-dev pkg-config zsh python3
COPY .. /root/repos/dotfiles-public
