[Editor]
BorderlessWindow = true
Transparent = 1.0
# RestoreWindowGeometry = true
IndentGuide = true
FontFamily = "HackGenNerd Console"
FontSize = 12
ExtPopupmenu = true
# ExtMessages = true
# ExtTabline = true
# ExtCmdline = true
# ModeEnablingIME = ["insert", "cmdline_normal"]
# SmoothScroll = true
# FileOpenCmd = ":e"
IgnoreFirstMouseClickWhenAppInactivated = true

[Cursor]
SmoothMove = true
Duration = 55

[Statusline]
Visible = true
ModeIndicatorType = "textLabel"

[Tabline]
Visible = true
ShowIcon = true

[Popupmenu]

[ScrollBar]
Visible = true

[MiniMap]
# Disable = false
Disable = true
Visible = true
Width = 80

[Markdown]
Disable = false
CodeHlStyle = "github"

[SideBar]
Visible = false
Width = 200
DropShadow = false
