# vim: set filetype=tmux :

set -g cursor-style block

set-option -sg escape-time 10
set-option -g focus-events on

set -g history-limit 50000
set -g display-time 4000
set -g set-clipboard on

set-option -g mouse on

setw -g mode-keys vi
