name: 'Neovim Benchmark'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup > repo] Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: '[Setup > vim-startuptime] Download'
        run: wget https://github.com/rhysd/vim-startuptime/releases/download/v1.3.1/vim-startuptime_1.3.1_linux_amd64.tar.gz
      - name: '[Setup > vim-startuptime] Extract'
        run: tar -xvf vim-startuptime_1.3.1_linux_amd64.tar.gz
      - name: '[Setup > vim-startuptime] Install'
        run: |
          mv vim-startuptime /usr/local/bin/vim-startuptime
          chmod +x /usr/local/bin/vim-startuptime

      - name: '[Setup > Neovim]'
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: '[Setup > Neovim] Install config'
        run: ./dotfiles install neovim
      - name: '[Setup > Neovim] Install plugins'
        run: nvim --headless -c 'Lazy! restore' -c 'qall'

      - name: '[Benchmark > Pre] Pull gh-pages branch'
        run: |
          git clean -f -d
          git checkout .
          git pull origin gh-pages --rebase

      - name: '[Benchmark]'
        run: vim-startuptime -vimpath nvim | tee ../result.txt
        env:
          TERM: screen-256color

      - name: '[Benchmark > Post] Download past results'
        run: |
          wget https://raw.githubusercontent.com/yuma140902/dotfiles-public/gh-pages/docs/benchmarks.json
      - name: '[Benchmark > Post] Parse result'
        run: python .github/scripts/vim_startuptime_to_json.py -i ../result.txt -o ./benchmarks.json -b ${GITHUB_REF##*/}
      - name: '[Benchmark > Post] Commit'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          create_branch: true
          commit_message: 'doc: update benchmarks.json [skip ci]'
          file_pattern: './benchmarks.json'
